image_topic: "/d400/color/image_raw"
cam_info_topic: "/d400/aligned_depth_to_color/camera_info"
depth_topic: "/d400/aligned_depth_to_color/image_raw"
mm_to_meters: true
image_freq: 30
min_depth: 0.8
max_depth: 4.0
odom_topic: "/odom"
#odom_freq: 20
#T_B_P: [0, 1, 0, 0, -1, 0, 0, 0, 0, 0 ,1 ,0, 0, 0, 0, 1]
#T_B_P: [0, 0, 1, 0, -1, 0, 0, 0, 0, -1 ,0 ,0, 0, 0, 0, 1]
#Kinect Fusion Odom
odom_freq: 30
odom_topic: "/kfusion/odom"
T_B_P: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0, 1] 
max_num_kfs: 10
